name: release.prod.jsonx

on:
  push:
    tags:
      - '*' # Run when any tag is pushed

jobs:
  pack_and_publish:
    name: Pack and publish to NuGet.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags and versioning

      - name: Setup .net core sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/JsonX/JsonX.csproj

      - name: Get package version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          CLEAN_TAG=${TAG#v} # remove leading 'v' if present
          echo "Package version: $CLEAN_TAG"
          echo "version=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name: Pack NuGet package
        run: |
          dotnet pack src/JsonX/JsonX.csproj \
            --configuration $BUILD_CONFIGURATION \
            --output ./packages \
            /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      - name: Publish package to NuGet.org
        run: |
          dotnet nuget push "./packages/**/*.nupkg" \
          --api-key ${{steps.login.outputs.NUGET_API_KEY}} 
          --source https://api.nuget.org/v3/index.json
